config:
 server:
   port: 5000
 database:
   host: mymongo
   port: 5223
   credentials:
     username: admin
     password: admin-password
   databasename: my-mongodb
   engine: mongodb
   schema: votings
  
